name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: davidcozens/cpputest:sha-5c26db9

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -B build

      - name: Build and test
        run: cmake --build build --target junit

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/cpputest_*.xml
