name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: davidcozens/cpputest:sha-ee85f20

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset debug

      - name: Build and test
        run: cmake --build --preset debug --target junit

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/debug/cpputest_*.xml

  sanitize:
    runs-on: ubuntu-latest
    container:
      image: davidcozens/cpputest:sha-ee85f20

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset sanitize

      - name: Build and test
        run: cmake --build --preset sanitize --target junit

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/sanitize/cpputest_*.xml
